# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - release
pr:
  - master


pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'



stages:


# Versioning feature branch and PR builds
- stage:
  displayName: Publish_PreRelease_Artifact
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Publish_PreRelease_Artifact
    steps:
      - task: GitVersion@5
        inputs:
          runtime: 'core'
      
      - task: DotNetCoreCLI@2
        displayName: "NuGet Restore"
        inputs:
          command: restore
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: "Build Solution"
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration) /p:Version=$(GitVersion.NuGetVersion)'
          versioningScheme: byBuildNumber
    
      - task: DotNetCoreCLI@2
        displayName: 'Pack (Prerelease)'
        inputs:
          command: pack
          packDirectory: '$(Build.ArtifactStagingDirectory)/packages/prereleases'
          nobuild: true
          versioningScheme: byEnvVar
          versionEnvVar: GitVersion.NuGetVersion

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'


# Versioning master branch builds

- stage:
  displayName: Publish_Release_Artifact
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  jobs:
  - job: Publish_Release_Artifact
    variables:
       patch: $[counter(variables['minor'], 0)]
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(major).$(minor).$(patch)"
        name: SetMasterBuildName
      - task: DotNetCoreCLI@2
        displayName: "NuGet Restore"
        inputs:
          command: restore
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: "Build Solution"
        inputs:
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
    
      - task: DotNetCoreCLI@2
        displayName: 'Create NuGet Package - Release Version'
        inputs:
          command: pack
          packDirectory: '$(Build.ArtifactStagingDirectory)/packages/releases'
          arguments: '--configuration $(buildConfiguration)'
          nobuild: true
          versioningScheme: 'byBuildNumber'


      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'



